import StyleDictionary from 'style-dictionary';

// 커스텀 포맷: CSS Variables
StyleDictionary.registerFormat({
  name: 'css/axis-variables',
  format: async ({ dictionary }) => {
    const tokens = dictionary.allTokens
      .map(token => `  --axis-${token.path.join('-')}: ${token.value};`)
      .join('\n');

    return `/**
 * AXIS Design System - Design Tokens
 * Generated by Style Dictionary
 * Do not edit directly
 */

:root {
${tokens}
}
`;
  }
});

// 커스텀 포맷: TypeScript 모듈
StyleDictionary.registerFormat({
  name: 'typescript/axis-module',
  format: async ({ dictionary }) => {
    const tokens = {};

    dictionary.allTokens.forEach(token => {
      let current = tokens;
      token.path.forEach((key, index) => {
        if (index === token.path.length - 1) {
          current[key] = token.value;
        } else {
          current[key] = current[key] || {};
          current = current[key];
        }
      });
    });

    return `/**
 * AXIS Design System - Design Tokens
 * Generated by Style Dictionary
 * Do not edit directly
 */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;

export default tokens;
`;
  }
});

// 커스텀 포맷: TypeScript 타입 정의
StyleDictionary.registerFormat({
  name: 'typescript/axis-declarations',
  format: async () => {
    return `/**
 * AXIS Design System - Design Tokens Type Definitions
 * Generated by Style Dictionary
 * Do not edit directly
 */

declare const tokens: {
  color: Record<string, Record<string, string> | string>;
  space: Record<string, string>;
  radius: Record<string, string>;
  font: {
    family: Record<string, string>;
    size: Record<string, string>;
    weight: Record<string, string>;
    lineHeight: Record<string, string>;
  };
  surface: Record<string, string>;
  text: Record<string, string>;
  border: Record<string, string>;
  icon: Record<string, string>;
  button: Record<string, Record<string, string>>;
  input: Record<string, Record<string, string>>;
  card: Record<string, Record<string, string>>;
  badge: Record<string, Record<string, string>>;
  dialog: Record<string, Record<string, string>>;
};

export = tokens;
`;
  }
});

const sd = new StyleDictionary({
  source: [
    'src/primitives/**/*.json',
    'src/semantic/light.json',
    'src/component/**/*.json'
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/css/',
      files: [{
        destination: 'variables.css',
        format: 'css/axis-variables'
      }]
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/js/',
      files: [
        {
          destination: 'tokens.mjs',
          format: 'typescript/axis-module'
        },
        {
          destination: 'tokens.js',
          format: 'javascript/module-flat'
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/axis-declarations'
        }
      ]
    },
    json: {
      transformGroup: 'js',
      buildPath: 'dist/json/',
      files: [{
        destination: 'tokens.json',
        format: 'json/flat'
      }]
    }
  }
});

console.log('Building AXIS Design Tokens...');
await sd.buildAllPlatforms();
console.log('Done!');
